image: node:24

variables:
  PNPM_VERSION: 10.10.0
  PNPM_STORE_DIR: .pnpm-store

cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - .pnpm-store/

before_script:
  - corepack enable
  - corepack prepare pnpm@$PNPM_VERSION --activate
  - pnpm config set store-dir $PNPM_STORE_DIR
  - pnpm install --frozen-lockfile

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - pnpm test
    - pnpm lint

pages:
  stage: deploy
  script:
    - pnpm build
    - rm -rf public
    - mv dist public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
